name: cluemaster-videoplayer-core
base: core20
version: '2025.06.24-DEV'
summary: Clumaster.io Video Player for Escape Rooms 
description: |
  ClueMaster Video Player is a Dynamic TV Display software for escape rooms.
  It loops through videos and plays them. To be used in small kiosk devices.
grade: stable 
confinement: strict

architectures:
  - amd64

apps:
  cluemaster-mediadisplay-core:
    daemon: simple
    restart-condition: always
    command-chain:
      - env-setup
    command: usr/local/bin/x11_kiosk_launch $SNAP/bin/desktop-launch $SNAP/bin/prepare-launch $SNAP/bin/python3 $SNAP/main.py
    environment:
      DISABLE_WAYLAND: 1

  pulseaudio:
    command: bin/pulseaudio
    daemon: simple
    restart-condition: always
    install-mode: enable

  pactl:
    command-chain: [bin/client-wrapper]
    command: usr/bin/pactl

  paplay:
    command-chain: [bin/client-wrapper]
    command: usr/bin/paplay

  parec:
    command-chain: [bin/client-wrapper]
    command: usr/bin/parec

  config:
    command: bin/config

  shell:
    command: bin/bash

plugs:
  playback:
    interface: audio-playback
  wayland:
  network:
  opengl:
  network-bind:
  shutdown:
  hardware-observe:
  alsa:

slots:
  audio-playback:

parts:
  copy-source-code:
    after: [desktop-qt5]
    plugin: dump
    source: cluemaster_videoplayer_source/
    stage-packages:
      - python3
      - bash
      - ffmpeg
      - libass9
      - alsa-base
      - locales
      - libvdpau1
      - i965-va-driver
      - va-driver-all
      - vdpau-driver-all
      - mesa-va-drivers
      - libvdpau-va-gl1
      - libglu1-mesa
      - samba-libs
      - git
      - python3-dbus
      - qtwayland5
      - mesa-utils
      - libgl1-mesa-dri
      - python3-pyqt5.qtmultimedia
      - libqt5multimedia5-plugins
      - python3-pyqt5.qtsvg
    stage:
      - -usr/share/alsa/alsa.conf
      - -usr/share/alsa/cards/HDA-Intel.conf
      - -usr/share/alsa/cards/USB-Audio.conf
      - -usr/share/alsa/cards/aliases.conf
      - -usr/share/alsa/pcm/center_lfe.conf
      - -usr/share/alsa/pcm/default.conf
      - -usr/share/alsa/pcm/dmix.conf
      - -usr/share/alsa/pcm/dsnoop.conf
      - -usr/share/alsa/pcm/front.conf
      - -usr/share/alsa/pcm/hdmi.conf
      - -usr/share/alsa/pcm/iec958.conf
      - -usr/share/alsa/pcm/modem.conf
      - -usr/share/alsa/pcm/rear.conf
      - -usr/share/alsa/pcm/side.conf
      - -usr/share/alsa/pcm/surround21.conf
      - -usr/share/alsa/pcm/surround40.conf
      - -usr/share/alsa/pcm/surround41.conf
      - -usr/share/alsa/pcm/surround50.conf
      - -usr/share/alsa/pcm/surround51.conf
      - -usr/share/alsa/pcm/surround71.conf
      - -usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
      - -usr/share/doc/libflac8/changelog.Debian.gz
      - -usr/lib/x86_64-linux-gnu/libfreetype.so.6.17.1
      - -usr/share/doc/libfreetype6/changelog.Debian.gz
      - -README.md
    stage-snaps: [mir-kiosk-x11]

  python-packages:
    after: [copy-source-code]
    plugin: python
    source: .
    build-packages:
      - python3-pip
      - python3-dev
      - gcc
      - build-essential
      - python3-wheel
      - libpq-dev
    stage-packages:
      - libpq5
    python-packages:
      - PyQt5 ~= 5.14.1
      - requests
      - git+https://github.com/ClueMaster-LLC/python-mpv
      - simplejson
      - psutil
      - gevent
      - websockets
      - GPUtil
    organize:
      usr/lib/*/samba/*: usr/lib/

  mpv:
    plugin: meson
    source: https://github.com/mpv-player/mpv.git
    source-tag: v0.35.0
    source-depth: 1
    build-packages:
      - python3
      - meson
      - cmake
      - ninja-build
      - build-essential
      - pkg-config
      - libasound2-dev
      - libx11-dev
      - libxext-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxss-dev
      - libgl1-mesa-dev
      - libegl1-mesa-dev
      - libwayland-dev
      - wayland-protocols
      - libdrm-dev
      - libavcodec-dev
      - libavfilter-dev
      - libavformat-dev
      - libswresample-dev
      - libswscale-dev
      - liblua5.2-dev
      - libfreetype6-dev
      - libjpeg-dev
      - libuchardet-dev
      - liblcms2-dev
      - libarchive-dev
      - libass-dev
      - libxkbcommon-dev
      - libxpresent-dev 
      - libva-dev
      - libvdpau-dev
    stage-packages:
      - liblcms2-2
      - libarchive13
      - liblua5.2-0
      - libuchardet0
      - libxpresent1
      - libva-wayland2
    meson-parameters:
      - --prefix=/usr
      - -Dlibmpv=true
      - -Dlua=lua52
      - -Dcplayer=true
      - -Dgl=enabled
      - -Dx11=enabled
      - -Dwayland=enabled
      - -Dvaapi=enabled
      - -Dvdpau=enabled
      - -Degl=enabled

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 
      - try: [appmenu-qt5]
      - locales-all
      - xdg-user-dirs
      - libdrm2
      - libgbm1
      - libdrm-intel1
      - libdrm-nouveau2
      - libdrm-radeon1
      - libegl1
      - libglapi-mesa
      - libglvnd0
      - libglx0
      - fcitx-frontend-qt5

    stage:
      - -usr/lib/x86_64-linux-gnu/libwebp.so.6.0.2
      - -usr/share/doc/libwebp6/changelog.Debian.gz

  pulseaudio-common:
    source: bin
    plugin: dump
    organize:
      client-wrapper: bin/client-wrapper
      config: bin/config
      pulseaudio: bin/pulseaudio

  alsa-lib:
    plugin: autotools
    source: https://github.com/alsa-project/alsa-lib.git
    source-tag: v1.2.5.1
    prime:
      - -usr/include
      - -usr/share/aclocal
      - -usr/lib/lib*.la
      - -usr/lib/pkgconfig

  pulseaudio:
    plugin: meson
    source: https://github.com/pulseaudio/pulseaudio.git
    source-tag: v15.0
    source-depth: 1
    after: [ alsa-lib ]
    build-packages:
      - check
      - doxygen
      - intltool
      - libapparmor-dev
      - libdbus-1-dev
      - libjson-c-dev
      - libglib2.0-dev
      - libspeexdsp-dev
      - libbluetooth-dev
      - libltdl-dev
      - libsndfile1-dev
      - libtdb-dev
      - libudev-dev
      - libasyncns-dev
      - libsbc-dev
      - libsnapd-glib-dev
      - libsoxr-dev
    stage-packages:
      - libapparmor1
      - libasyncns0
      - libbluetooth3
      - libflac8
      - libglib2.0-0
      - libgomp1
      - libjson-c4
      - libltdl7
      - libogg0
      - libsbc1
      - libsnapd-glib1
      - libsndfile1
      - libsoxr0
      - libsoxr-lsr0
      - libspeexdsp1
      - libtdb1
      - libudev1
      - libvorbis0a
      - libvorbisenc2
    meson-parameters:
      - --prefix="/usr"
      - --sysconfdir=/etc
      - --libexec=/usr/lib
      - --libdir=/usr/lib
      - --localstatedir=/var
      - -Dgstreamer="disabled"
      - -Dbluez5-gstreamer="disabled"
      - -Dorc="disabled"
      - -Dgsettings="disabled"
      - -Dadrian-aec="false"
      - -Dgtk="disabled"
      - -Dhal-compat="false"
      - -Dwebrtc-aec="disabled"
      - -Doss-output="disabled"
      - -Djack="disabled"
      - -Dx11="disabled"
      - -Dsystem_user="root"
      - -Dsystem_group="root"
      - -Daccess_group="root"
    override-build: |
      snapcraftctl build
      VER=$(cd $SNAPCRAFT_PART_SRC; git tag|sed 's/^v//')
      snapcraftctl set-version $VER
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
    override-prime: |
      snapcraftctl prime
      find usr/share/doc/ -type f,l ! -name copyright | xargs rm -rf
    prime:
      - -usr/include
      - -usr/share/zsh
      - -usr/share/bash-completion
      - -usr/share/man
      - -usr/share/GConf
      - -usr/share/lintian
      - -usr/share/vala
      - -usr/libexec
      - -usr/lib/cmake
      - -usr/lib/pkgconfig
      - -usr/lib/systemd
      - -etc/dconf

  alsa-plugins:
    plugin: autotools
    source: https://github.com/alsa-project/alsa-plugins.git
    source-tag: v1.2.5
    after: [ pulseaudio, alsa-lib ]
    autotools-configure-parameters:
      - --prefix=/usr
      - --with-alsalconfdir=/etc/alsa/conf.d
      - --sysconfdir=/etc/alsa/conf.d
    prime:
      - -usr/lib/alsa-lib/*.la
    override-prime: |
      snapcraftctl prime
      # make links relative
      cd etc/alsa/conf.d
      for link in $(find . -type l); do
        newlink=$(readlink $link|sed 's;^/;../../../;')
        ln -sf $newlink $link
      done
      cd -

  alsa-ucm:
    plugin: dump
    source: https://github.com/alsa-project/alsa-ucm-conf.git
    source-tag: v1.2.5.1
    after: [ alsa-plugins ]
    organize:
      ucm: usr/share/alsa/ucm
      ucm2: usr/share/alsa/ucm2
    prime:
      - -README.md

  extras:
    plugin: dump
    source: static/
    organize:
      "prepare-launch": "bin/"

environment:
  LD_LIBRARY_PATH: "$SNAP/usr/lib/pulseaudio:$SNAP/usr/lib/alsa-lib"
  PULSE_RUNTIME_PATH: /var/run/pulse
  PULSE_STATE_PATH: $SNAP_COMMON/state
  ALSA_CONFIG_UCM: $SNAP/usr/share/alsa/ucm2
  ALSA_CONFIG_TPLG: $SNAP/usr/share/alsa/topology
  ALSA_CONFIG_PATH: $SNAP/usr/share/alsa/alsa.conf
  ALSA_MIXER_SIMPLE: $SNAP/usr/share/alsa/smixer.conf
  ALSA_PLUGIN_DIR: $SNAP/usr/lib/alsa-lib


layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/local/share/fonts:
    bind: $SNAP/usr/local/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /etc/pulse:
    bind: $SNAP/etc/pulse
  /etc/alsa:
    bind: $SNAP/etc/alsa
  /var/lib/pulse:
    bind: $SNAP_DATA
  /usr/lib/pulse-15.0:
    symlink: $SNAP/usr/lib/pulse-15.0
  /usr/lib/alsa-lib:
    bind: $SNAP/usr/lib/alsa-lib
  /usr/share/pulseaudio:
    symlink: $SNAP/usr/share/pulseaudio
  /usr/share/alsa:
    symlink: $SNAP/usr/share/alsa
  /usr/share/applications:
    bind: $SNAP/usr/share/applications
